# Generated by Django 3.2.14 on 2022-12-04 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_schedule_user_video'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='video',
            unique_together=set(),
        ),
        migrations.AlterModelTable(
            name='schedule',
            table=None,
        ),
        migrations.AlterModelTable(
            name='video',
            table=None,
        ),
    ]
