# Generated by Django 3.2.14 on 2022-12-09 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20221204_1558'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='schedule',
            table='schedule',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
        migrations.AlterModelTable(
            name='video',
            table='video',
        ),
    ]
