# Generated by Django 3.2.14 on 2022-12-28 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_teach'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teach',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
