# Generated by Django 3.2.14 on 2022-12-28 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0008_alter_teach_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='online',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
