# Generated by Django 3.2.14 on 2022-12-30 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0009_user_online'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
