# Generated by Django 3.2.14 on 2022-12-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ufile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.IntegerField()),
                ('cid', models.CharField(default='', max_length=4)),
                ('vfile', models.FileField(upload_to='static/media<django.db.models.fields.IntegerField>/<django.db.models.fields.CharField>')),
            ],
            options={
                'db_table': 'Ufile',
            },
        ),
        migrations.RemoveField(
            model_name='video',
            name='vfile',
        ),
    ]
